# Generated by Django 4.0.6 on 2022-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Age',
            new_name='Password',
        ),
        migrations.AlterField(
            model_name='datas',
            name='image',
            field=models.ImageField(blank=True, default='imges/IMG_20210820_065426.jpg', null=True, upload_to='imges/'),
        ),
    ]
